skin_templates.xml: Cast to integer to fix crash
[Screen] Showing screen 'MenuSummary'.
[Screen] Showing screen '['menu_mainmenu', 'Menu']'.
TypeError: 'float' object cannot be interpreted as an integer

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/usr/lib/enigma2/python/Plugins/Extensions/LCD4linux/plugin.py", line 8581, in CallCheckRefresh
    self.CheckRefresh.stop()